import "./globals.css";
export const metadata = {
  title: {
    default:'NExt APP'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" w-full  text-white font-[poppins] font-medium bg-blue-950">{children}</body>
    </html>
  )
}
